import React, {useEffect} from 'react';
import {useSession} from "next-auth/react";
import Head from "next/head";
import AdminLayout from "../../components/layout/adminLayout";
import {AdminProvider} from "../../context/adminContext";
import FileStructure from "../../components/admin/fileStructure";

const Index = () => {
    const {data: session, status} = useSession();

    //if authenticated and admin, render page

    //if authenticated and not admin, redirect to home

    //if not authenticated, redirect to login


    return (
        <>
            <AdminProvider>
                <Head>
                    <title>joeri - admin</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/icon.svg"/>
                </Head>
                <AdminLayout>
                    <main className="h-full bg-midnight text-lynch">
                        <FileStructure/>
                    </main>
                </AdminLayout>
            </AdminProvider>
        </>
    );
};

export default Index;
