import React, {FormEvent, useState} from 'react';
import Head from "next/head";
import {signIn, useSession} from "next-auth/react";
import {useRouter} from "next/router";

const LoginPage = () => {
    const router = useRouter();
    const { data: session } = useSession();

    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();

        await signIn('credentials', { email, password });
    };

    return (
        <>
            <Head>
                <title>joeri - about</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/icon.svg"/>
            </Head>
            <div>
                <button onClick={() => signIn()}>test</button>
                <form onSubmit={(e) => handleSubmit(e)} className="mt-20">
                    <div
                        className="flex flex-col items-center justify-center min-h-screen py-2 -mt-56 px-14 text-center">
                        <div
                            className="flex flex-col items-center justify-center w-full max-w-md px-4 py-6 space-y-8 bg-white border-2 border-gray-300 rounded-lg shadow-xl">
                            <div className="flex flex-col items-center justify-center w-full space-y-2">
                                <h1 className="text-3xl font-bold text-gray-900">Login</h1>
                                <p className="text-sm text-gray-500">No account yet? <button
                                    type="button"
                                    onClick={() => router.push('/auth/register')}
                                    className="font-medium text-indigo-600 hover:text-indigo-500">Register</button>
                                </p>
                            </div>
                            <div className="w-full space-y-6">
                                <div className="flex flex-col w-full space-y-1">
                                    <label htmlFor="email" className="text-sm font-medium text-gray-900">Email</label>
                                    <input type="email" value={email} onChange={(e) => setEmail(e.target.value)}
                                           placeholder="email" id="email"
                                           className="w-full px-4 py-2 text-sm text-gray-900 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"/>
                                </div>
                                <div className="flex flex-col w-full space-y-1">
                                    <label htmlFor="password"
                                           className="text-sm font-medium text-gray-900">Password</label>
                                    <input type="password" value={password}
                                           onChange={(e) => setPassword(e.target.value)} placeholder="password"
                                           id="password"
                                           className="w-full px-4 py-2 text-sm text-gray-900 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"/>
                                </div>
                                <div>
                                    <button type="submit"
                                            className="w-full px-4 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md hover:bg-indigo-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-indigo-500">Login
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                {session?.user && (
                    <div>
                        <h1>{session.user.firstName} {session.user.lastName}</h1>
                    </div>
                )}
            </div>
        </>

    );
};

export default LoginPage;
