import React from 'react';
import Layout from "../../components/layout/layout";
import Head from "next/head";

const Settings = () => {
    return (
        <>
            <Head>
                <title>joeri - settings</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/icon.svg"/>
            </Head>
            <Layout>
                <main className="h-full min-h-screen lg:h-screen bg-midnight">
                </main>
            </Layout>
        </>
    );
};

export default Settings;
