import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '../styles/Home.module.css'
import Layout from "../components/layout/layout";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>joeri - hello</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <main
                    className="h-screen overflow-y-hidden w-screen px-7 flex flex-col lg:flex-row lg:justify-center lg:space-x-10 xl:space-x-20 2xl:space-x-36 space-y-10 bg-no-repeat bg-cover bg-center bg-[url('/main_bg_mobile.svg')] lg:bg-[url('/main_bg.svg')]">
                    <div className="h-full flex flex-col justify-between lg:justify-center lg:space-y-20">
                        <div className="mt-40 text-mystic space-y-5">
                            <p className="text-lg">Hi all. I am</p>
                            <h1 className="text-7xl">Joeri <br/> Schenk</h1>
                            <p className="text-xl text-turquoise font-medium">&gt; Software engineer</p>
                        </div>
                        <div className="pb-20 space-y-2">
                            <p className="text-lynch hidden lg:flex">
                                // complete the game to continue
                            </p>
                            <p className="text-lynch hidden lg:flex">
                                // you can also view the source code on my github page
                            </p>
                            <p className="text-lynch lg:hidden">
                                // find my profile on Github:
                            </p>
                            <p className="text-white">
                            <span className="text-[#4D5BCE]">
                                const
                            </span>
                                {" "}
                                <span className="text-turquoise">
                                {" "}githublink
                            </span>
                                {" "}= <span className="text-[#E99287]">"https://github.com/joeri157"</span>;
                            </p>
                        </div>
                    </div>
                    <div className="hidden lg:flex">
                        <img src="/game.svg" alt=""/>
                    </div>
                </main>
            </Layout>
        </>
    )
}
