import React, {FormEvent, useEffect, useState} from 'react';
import {selectAuth, setToken} from "../redux/slices/authSlice";
import {useAppDispatch, useAppSelector} from "../redux/store";
import {login, logout, register} from "../redux/thunks/authThunks";
import Head from "next/head";

const LoginPage = () => {
    const dispatch = useAppDispatch();
    const {status, token, user} = useAppSelector(selectAuth);
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    useEffect(() => {
        token && localStorage.setItem('token', token);

    }, [token]);


    useEffect(() => {
        switch (status) {
            case 200:
                alert('Logged in successfully');
                break;
            case 401:
                alert('Invalid credentials');
                break;
            case 201:
                alert('Registered successfully');
                break;
            case 400:
                alert('Invalid credentials');
                break;
            default:
                break;

        }
    }, [status]);

    const handleSubmit = async (e: FormEvent) => {
        e.preventDefault();

        dispatch(login({email, password}));
    };


    const handleLogout = async (e: FormEvent) => {
        e.preventDefault();

        dispatch(logout({accessToken: localStorage.getItem('token')}));
    };

    return (
        <>
            <Head>
                <title>joeri - about</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/icon.svg"/>
            </Head>
            <div>
                <form onSubmit={handleSubmit} className="mt-20">
                    <div
                        className="flex flex-col items-center justify-center min-h-screen py-2 -mt-56 px-14 text-center">
                        <div
                            className="flex flex-col items-center justify-center w-full max-w-md px-4 py-6 space-y-8 bg-white border-2 border-gray-300 rounded-lg shadow-xl">
                            <div className="flex flex-col items-center justify-center w-full space-y-2">
                                <h1 className="text-3xl font-bold text-gray-900">Register</h1>
                                <p className="text-sm text-gray-500">Already have an account? <button
                                    className="font-medium text-indigo-600 hover:text-indigo-500">Login</button>
                                </p>
                            </div>
                            <div className="w-full space-y-6">
                                <div className="flex flex-col w-full space-y-1">
                                    <label htmlFor="email" className="text-sm font-medium text-gray-900">Email</label>
                                    <input type="email" value={email} onChange={(e) => setEmail(e.target.value)}
                                           placeholder="email" id="email"
                                           className="w-full px-4 py-2 text-sm text-gray-900 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"/>
                                </div>
                                <div className="flex flex-col w-full space-y-1">
                                    <label htmlFor="password"
                                           className="text-sm font-medium text-gray-900">Password</label>
                                    <input type="password" value={password}
                                           onChange={(e) => setPassword(e.target.value)} placeholder="password"
                                           id="password"
                                           className="w-full px-4 py-2 text-sm text-gray-900 border border-gray-300 rounded-md focus:outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
                {user && (
                    <div>
                        <h1>{user.email}</h1>
                    </div>
                )}
                <button onClick={handleLogout}>logout</button>
            </div>
        </>

    );
};

export default LoginPage;
