import React from 'react';
import Head from "next/head";
import Layout from "../components/layout/layout";
import Filter from "../components/projects/filter";
import {useAppDispatch, useAppSelector} from "../redux/store";
import {selectFilter} from "../redux/slices/filterSlice";

const Projects = () => {
    const activeFilter = useAppSelector(selectFilter)
    const dispatch = useAppDispatch()

    console.log(activeFilter)

    return (
        <>
            <Head>
                <title>joeri - projects</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <main className="h-full min-h-screen lg:h-screen bg-midnight">
                    <div className="pt-20 pb-6 lg:hidden">
                        <p className="text-white px-5 pb-6">_projects</p>
                        <div>
                            <Filter/>
                        </div>
                        <div className="py-5 px-5">
                            <p className={`${activeFilter.length === 0 ? "hidden" : ""}`}>&#47;&#47; projects &#47;{activeFilter.map((item, index) => {
                                return (
                                    <span key={index}> {item}</span>
                                )
                            })}
                            </p>
                            {activeFilter.length === 0 &&
                                <p className={`${activeFilter.length === 0 ? "" : "hidden"}`}>&#47;&#47; projects &#47; All</p>}
                        </div>
                    </div>
                </main>
            </Layout>
        </>
    );
};

export default Projects;
